namespace Rivoltante.Bonfire;

public enum ReceiveEventType
{
    Error,
    Authenticated,
    Bulk,
    Pong,
    Ready,
    Message,
    MessageUpdate,
    MessageAppend,
    MessageDelete,
    MessageReact,
    MessageUnreact,
    MessageRemoveReaction,
    ChannelCreate,
    ChannelUpdate,
    ChannelDelete,
    ChannelGroupJoin,
    ChannelGroupLeave,
    ChannelStartTyping,
    ChannelStopTyping,
    ChannelAck,
    ServerCreate,
    ServerUpdate,
    ServerDelete,
    ServerMemberUpdate,
    ServerMemberJoin,
    ServerMemberLeave,
    ServerRoleUpdate,
    ServerRoleDelete,
    UserUpdate,
    UserRelationship,
    UserPlatformWipe,
    EmojiCreate,
    EmojiDelete
    //Auth
}